// client/src/lib/components/CommentCreate.svelte
<script lang="ts">
	import { enhance } from '$app/forms';
	import Button from './Button.svelte';
	import Input from './Input.svelte';

	export let postId = '';
</script>

<form method="POST" action="?/comment" use:enhance class="flex flex-col gap-5">
	<div class="hidden">
		<Input id="postId" label="Post ID" name="postId" type="hidden" value={postId} />
	</div>
	<Input id="content" label="Comment" name="content" type="text" />
	<Button label="Comment" type="submit" />
</form>

// client/src/components/CommentCreate.tsx
import { FormEvent, useState } from 'react';
import axios from 'axios';
import Input from './Input';
import Button from './Button';

type Props = {
  postId: string;
};
export default function CommentCreate({ postId }: Props) {
  const [content, setContent] = useState('');
  const handleSubmit = async (event: FormEvent) => {
    event.preventDefault();
    await axios.post(`http://posts.com/posts/${postId}/comments`, {
      content,
    });

    setContent('');
  };
  return (
    <form onSubmit={handleSubmit} className="flex flex-col gap-5">
      <Input
        id="content"
        label="Comment"
        name="content"
        type="text"
        value={content}
        onChange={(e) => setContent(e.target.value)}
      />
      <Button label="Comment" type="submit" />
    </form>
  );
}
