// 1.blog/client/src/components/PostCreate.tsx
import { FormEvent, useState } from 'react';
import axios from 'axios';
import Input from './Input';
import Button from './Button';

export default function PostCreate() {
  const [title, setTitle] = useState('');
  const [content, setContent] = useState('');

  const handleSubmit = async (event: FormEvent) => {
    event.preventDefault();

    await axios.post('http://posts.com/posts/create', {
      title,
      content,
    });

    setTitle('');
    setContent('');
  };
  return (
    <form
      onSubmit={handleSubmit}
      className="my-10 grid gap-5 rounded-xl shadow-lg border-[0.5px] bg-[#A2D2FF] p-10"
    >
      <Input
        id="title"
        label="Title"
        name="title"
        type="text"
        value={title}
        onChange={(e) => setTitle(e.target.value)}
      />
      <Input
        id="content"
        label="Content"
        name="content"
        type="text"
        value={content}
        onChange={(e) => setContent(e.target.value)}
      />

      <Button type="submit" label="Submit" />
    </form>
  );
}

// client/src/lib/components/PostCreate.svelte
<script lang="ts">
	import { enhance } from '$app/forms';
	import Button from './Button.svelte';
	import Input from './Input.svelte';
</script>

<form
	method="POST"
	action="?/create"
	use:enhance
	class="my-10 grid gap-5 rounded-xl shadow-lg border-[0.5px] bg-[#A2D2FF] p-10"
>
	<Input id="title" label="Title" name="title" />
	<Input id="content" label="Content" name="content" />

	<Button type="submit" label="Submit" />
</form>
<hr />
